language: php

matrix:
    include:
        - php: 5.5
          env: APCU_VERSION="4.0.11"
        - php: 5.6
          env:
            - APCU_VERSION="4.0.11"
            - CODE_COVERAGE=true
        - php: 7.0
          env: APCU_VERSION="5.1.5"
    allow_failures:
        - php: 5.6
        - php: 7.0
    fast_finish: true

before_install:
    - composer self-update

install:
    - echo '' | pecl install apcu-$APCU_VERSION
    - if [[ $(phpenv version-name) == "7.0" ]]; then
        echo "extension = apc.so" >> ~/.phpenv/versions/7.0/etc/php.ini ;
      fi
    - travis_retry composer install --no-interaction --prefer-source
    
before_script:
    - phpenv config-add tests/apc.ini

script:
    - if [[ $CODE_COVERAGE == 'true' ]]; then
        composer exec phpunit -- --coverage-clover clover.xml ; else
        composer exec phpunit ;
      fi

after_success:
    - if [[ $CODE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
