language: php

php:
    - 5.5

before_install:
    - composer self-update

install:
    - echo '' | pecl install apcu-4.0.10
    - travis_retry composer install --no-interaction --prefer-source
    
before_script:
    - phpenv config-add tests/apc.ini

script:
    - ./vendor/bin/phpunit