language: php

matrix:
    include:
        - php: 5.5
          env: APCU_VERSION="4.0.11"
        - php: 5.6
          env:
            - APCU_VERSION="4.0.11"
            - COVERAGE_CLOVER=true
        - php: 7.0
          env: APCU_VERSION="5.1.5"
    allow_failures:
        - php: 7.0
    fast_finish: true

before_install:
    - echo yes | pecl install apcu-$APCU_VERSION
    - phpenv config-add tests/apc.ini
    - composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - if [[ $COVERAGE_CLOVER == 'true' ]]; then
        composer exec phpunit -- --coverage-clover clover.xml ;
      else
        composer exec phpunit ;
      fi

after_success:
    - if [[ $COVERAGE_CLOVER == 'true' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
